apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-label02
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        environment: production
        release: beta
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80