apiVersion: v1
entries:
  mysql-addct:
  - apiVersion: v1
    appVersion: 5.7.30
    created: "2021-06-17T11:07:04.134338+09:00"
    deprecated: true
    description: DEPRECATED - Fast, reliable, scalable, and easy to use open-source relational database system.
    digest: 23a10b4f1e2ad1925d566f59df2a2a217635b2edcd73d99181320994589c95e3
    home: https://www.mysql.com/
    icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
    keywords:
    - mysql
    - database
    - sql
    name: mysql-addct
    sources:
    - https://github.com/kubernetes/charts
    - https://github.com/docker-library/mysql
    urls:
    - charts/mysql-addct-0.1.1.tgz
    version: 0.1.1
generated: "2021-06-17T11:07:04+09:00"
serverInfo: {}
