apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-app
spec:
  selector:
    matchLabels:
      k8s-app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:7.3.6
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: GF_SERVER_HTTP_PORT
          value: "3000"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          value: /
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: grafana-app
  name: grafana-app
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
  selector:
    k8s-app: grafana
  type: NodePort