# NOTE: kustomize is not supported. This file exists only to be able to reference it from bases.
# https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#bases
#
# ```
# namespace: ingress-nginx
# bases:
#   - github.com/kubernetes/ingress-nginx/deploy/static/provider/do?ref=master
# ```

resources:
  - deploy.yaml
